import type {
  Lead,
  Alert,
  DailyReport,
  PlatformConfig,
  DashboardStats,
  ChartDataPoint,
  Platform,
} from "./types";

// Fixed base time to avoid hydration mismatch (Feb 26, 2026 12:00 UTC)
const BASE_TIME = new Date("2026-02-26T12:00:00Z").getTime();

// ── Leads ───────────────────────────────────────────────────────────

export const leads: Lead[] = [
  {
    id: "lead-001",
    platform: "Facebook",
    source: "GHL Agency Owners",
    username: "Sarah Mitchell",
    text: "Looking for a virtual assistant who can manage my GoHighLevel account. Need someone ASAP to handle client onboarding workflows and appointment scheduling. Budget is $800-1200/month. Must be US-based or willing to work US hours.",
    url: "https://facebook.com/groups/ghl-agency/posts/12345",
    intentScore: 92,
    intentLevel: "High",
    intentCategory: "Direct Hiring",
    status: "New",
    engagement: 14,
    location: "United States",
    matchedKeywords: ["looking for a virtual assistant", "GoHighLevel", "ASAP", "appointment scheduling"],
    createdAt: new Date(BASE_TIME - 15 * 60000),
  },
  {
    id: "lead-002",
    platform: "LinkedIn",
    source: "Virtual Assistant Network",
    username: "James Rodriguez",
    text: "Our agency is scaling fast and we urgently need to hire 2-3 virtual assistants for CRM management and lead follow-up. Experience with HubSpot or Salesforce preferred. Remote, full-time positions available immediately.",
    url: "https://linkedin.com/feed/update/67890",
    intentScore: 95,
    intentLevel: "High",
    intentCategory: "Direct Hiring",
    status: "Contacted",
    engagement: 28,
    location: "United Kingdom",
    matchedKeywords: ["hire", "virtual assistants", "CRM", "HubSpot", "urgently"],
    createdAt: new Date(BASE_TIME - 45 * 60000),
    assignedTo: "Alex Kim",
  },
  {
    id: "lead-003",
    platform: "Reddit",
    source: "r/Entrepreneur",
    username: "u/digital_nomad_ceo",
    text: "Can anyone recommend a good virtual assistant service? I'm drowning in admin work — emails, scheduling, invoicing. Spending 3+ hours daily on stuff that could be delegated. What do you guys use?",
    url: "https://reddit.com/r/Entrepreneur/comments/abc123",
    intentScore: 72,
    intentLevel: "Medium",
    intentCategory: "Recommendation Request",
    status: "New",
    engagement: 45,
    location: "Canada",
    matchedKeywords: ["recommend a good virtual assistant", "drowning in admin", "delegated"],
    createdAt: new Date(BASE_TIME - 2 * 3600000),
  },
  {
    id: "lead-004",
    platform: "X",
    source: "Search: hiring VA",
    username: "@realestate_mike",
    text: "Thinking about hiring a VA to manage my real estate leads and CRM. Anyone have experience with real estate VAs? What should I expect to pay? Is $500/mo reasonable for part-time?",
    url: "https://x.com/realestate_mike/status/111222333",
    intentScore: 65,
    intentLevel: "Medium",
    intentCategory: "Budget Inquiry",
    status: "New",
    engagement: 8,
    location: "United States",
    matchedKeywords: ["hiring a VA", "CRM", "real estate VAs"],
    createdAt: new Date(BASE_TIME - 3 * 3600000),
  },
  {
    id: "lead-005",
    platform: "Facebook",
    source: "Online Business Owners",
    username: "Maria Chen",
    text: "I need someone to handle my social media management and email marketing. Running a Shopify store and can't keep up with content creation, customer support emails, and Facebook ads. Hiring immediately — please DM with rates.",
    url: "https://facebook.com/groups/online-biz/posts/44556",
    intentScore: 88,
    intentLevel: "High",
    intentCategory: "Direct Hiring",
    status: "Qualified",
    engagement: 22,
    location: "Australia",
    matchedKeywords: ["hiring immediately", "social media management", "email marketing", "Facebook ads"],
    createdAt: new Date(BASE_TIME - 5 * 3600000),
    assignedTo: "Jordan Lee",
  },
  {
    id: "lead-006",
    platform: "LinkedIn",
    source: "Startup Founders Group",
    username: "David Park",
    text: "How much does a good executive virtual assistant cost these days? Our startup is at the point where I'm spending too much time on admin tasks instead of building product. Need someone for calendar management, travel booking, and inbox zero.",
    url: "https://linkedin.com/feed/update/99887",
    intentScore: 58,
    intentLevel: "Medium",
    intentCategory: "Budget Inquiry",
    status: "New",
    engagement: 16,
    location: "United States",
    matchedKeywords: ["virtual assistant cost", "admin tasks", "calendar management"],
    createdAt: new Date(BASE_TIME - 8 * 3600000),
  },
  {
    id: "lead-007",
    platform: "Facebook",
    source: "ClickFunnels Users",
    username: "Ryan Thompson",
    text: "Need a VA who knows ClickFunnels and Zapier. Building out automated funnels for my coaching business and need help with tech setup, email sequences, and lead management. This is a long-term position.",
    url: "https://facebook.com/groups/cf-users/posts/77889",
    intentScore: 85,
    intentLevel: "High",
    intentCategory: "Technical VA Request",
    status: "New",
    engagement: 11,
    location: "United States",
    matchedKeywords: ["need a VA", "ClickFunnels", "Zapier", "lead management"],
    createdAt: new Date(BASE_TIME - 10 * 3600000),
  },
  {
    id: "lead-008",
    platform: "Reddit",
    source: "r/smallbusiness",
    username: "u/solopreneur_life",
    text: "Too many client messages, too many emails, invoicing is behind. I think it's time to finally outsource some of this admin work. Anyone gone through this transition? What tasks did you delegate first?",
    url: "https://reddit.com/r/smallbusiness/comments/def456",
    intentScore: 48,
    intentLevel: "Low",
    intentCategory: "Delegation Signal",
    status: "Dismissed",
    engagement: 32,
    matchedKeywords: ["too many client messages", "outsource", "admin work"],
    createdAt: new Date(BASE_TIME - 14 * 3600000),
  },
  {
    id: "lead-009",
    platform: "X",
    source: "Search: need VA",
    username: "@coach_jessica",
    text: "Officially looking for a virtual assistant! Need help with appointment booking, client follow-ups, and managing my CRM (I use GoHighLevel). DM me if you know someone reliable. US timezone preferred.",
    url: "https://x.com/coach_jessica/status/444555666",
    intentScore: 90,
    intentLevel: "High",
    intentCategory: "Direct Hiring",
    status: "Contacted",
    engagement: 19,
    location: "United States",
    matchedKeywords: ["looking for a virtual assistant", "appointment booking", "CRM", "GoHighLevel"],
    createdAt: new Date(BASE_TIME - 18 * 3600000),
    assignedTo: "Alex Kim",
  },
  {
    id: "lead-010",
    platform: "Facebook",
    source: "Digital Marketing Agency",
    username: "Tom Nguyen",
    text: "We're hiring 5 VAs for our agency. Need people experienced in social media scheduling, content writing, and basic graphic design using Canva. Full training provided. $4-6/hr depending on experience.",
    url: "https://facebook.com/groups/dma/posts/22334",
    intentScore: 82,
    intentLevel: "High",
    intentCategory: "Direct Hiring",
    status: "New",
    engagement: 67,
    location: "United States",
    matchedKeywords: ["hiring", "VAs", "social media", "content writing"],
    createdAt: new Date(BASE_TIME - 22 * 3600000),
  },
  {
    id: "lead-011",
    platform: "LinkedIn",
    source: "E-commerce Entrepreneurs",
    username: "Lisa Wang",
    text: "Best VA services for e-commerce? Need help with order processing, customer service emails, and inventory management on Shopify. What platforms are people using to find qualified VAs?",
    url: "https://linkedin.com/feed/update/55667",
    intentScore: 62,
    intentLevel: "Medium",
    intentCategory: "Recommendation Request",
    status: "New",
    engagement: 24,
    matchedKeywords: ["VA services", "customer service", "find qualified VAs"],
    createdAt: new Date(BASE_TIME - 26 * 3600000),
  },
  {
    id: "lead-012",
    platform: "Reddit",
    source: "r/RemoteWork",
    username: "u/agency_owner_2026",
    text: "Scaling my marketing agency and need to hire a cold calling VA and an appointment setter. Budget $800-1500/month total. Where's the best place to find reliable VAs who specialize in outbound?",
    url: "https://reddit.com/r/RemoteWork/comments/ghi789",
    intentScore: 78,
    intentLevel: "Medium",
    intentCategory: "Direct Hiring",
    status: "New",
    engagement: 18,
    location: "Canada",
    matchedKeywords: ["hire", "cold calling VA", "appointment setter"],
    createdAt: new Date(BASE_TIME - 30 * 3600000),
  },
];

// ── Alerts ──────────────────────────────────────────────────────────

export const alerts: Alert[] = leads
  .filter((l) => l.intentScore >= 70)
  .map((l) => ({
    id: `alert-${l.id}`,
    leadId: l.id,
    platform: l.platform,
    intentScore: l.intentScore,
    snippet: l.text.slice(0, 140) + "...",
    username: l.username,
    source: l.source,
    createdAt: l.createdAt,
    read: l.status !== "New",
  }));

// ── Dashboard Stats ─────────────────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalLeads: 247,
  highIntentLeads: 64,
  avgIntentScore: 71,
  responseRate: 78,
  totalLeadsChange: 12.5,
  highIntentChange: 8.3,
  avgScoreChange: 3.2,
  responseRateChange: -2.1,
};

// ── Chart Data (7 days) ─────────────────────────────────────────────

export const chartData: ChartDataPoint[] = [
  { date: "Feb 20", leads: 28, highIntent: 8 },
  { date: "Feb 21", leads: 35, highIntent: 11 },
  { date: "Feb 22", leads: 22, highIntent: 6 },
  { date: "Feb 23", leads: 41, highIntent: 14 },
  { date: "Feb 24", leads: 38, highIntent: 10 },
  { date: "Feb 25", leads: 45, highIntent: 12 },
  { date: "Feb 26", leads: 38, highIntent: 9 },
];

// ── Platform Breakdown ──────────────────────────────────────────────

export const platformBreakdown: { platform: Platform; count: number; percentage: number }[] = [
  { platform: "Facebook", count: 98, percentage: 40 },
  { platform: "LinkedIn", count: 69, percentage: 28 },
  { platform: "Reddit", count: 49, percentage: 20 },
  { platform: "X", count: 31, percentage: 12 },
];

// ── Platform Configs ────────────────────────────────────────────────

export const platformConfigs: PlatformConfig[] = [
  {
    platform: "Facebook",
    enabled: true,
    postsPerMinute: 10,
    lastActive: new Date(BASE_TIME - 2 * 60000),
    totalDetected: 98,
  },
  {
    platform: "LinkedIn",
    enabled: true,
    postsPerMinute: 5,
    lastActive: new Date(BASE_TIME - 5 * 60000),
    totalDetected: 69,
  },
  {
    platform: "Reddit",
    enabled: true,
    postsPerMinute: 8,
    lastActive: new Date(BASE_TIME - 12 * 60000),
    totalDetected: 49,
  },
  {
    platform: "X",
    enabled: false,
    postsPerMinute: 6,
    totalDetected: 31,
  },
];

// ── Daily Reports ───────────────────────────────────────────────────

export const dailyReports: DailyReport[] = [
  {
    date: "2026-02-26",
    totalLeads: 38,
    highIntent: 9,
    mediumIntent: 17,
    lowIntent: 12,
    platforms: { Facebook: 15, LinkedIn: 10, Reddit: 8, X: 5 },
    topLeads: leads.slice(0, 3),
  },
  {
    date: "2026-02-25",
    totalLeads: 45,
    highIntent: 12,
    mediumIntent: 20,
    lowIntent: 13,
    platforms: { Facebook: 18, LinkedIn: 12, Reddit: 9, X: 6 },
    topLeads: leads.slice(2, 5),
  },
  {
    date: "2026-02-24",
    totalLeads: 38,
    highIntent: 10,
    mediumIntent: 16,
    lowIntent: 12,
    platforms: { Facebook: 14, LinkedIn: 11, Reddit: 8, X: 5 },
    topLeads: leads.slice(4, 7),
  },
  {
    date: "2026-02-23",
    totalLeads: 41,
    highIntent: 14,
    mediumIntent: 15,
    lowIntent: 12,
    platforms: { Facebook: 16, LinkedIn: 10, Reddit: 10, X: 5 },
    topLeads: leads.slice(1, 4),
  },
  {
    date: "2026-02-22",
    totalLeads: 22,
    highIntent: 6,
    mediumIntent: 10,
    lowIntent: 6,
    platforms: { Facebook: 9, LinkedIn: 6, Reddit: 4, X: 3 },
    topLeads: leads.slice(5, 8),
  },
  {
    date: "2026-02-21",
    totalLeads: 35,
    highIntent: 11,
    mediumIntent: 14,
    lowIntent: 10,
    platforms: { Facebook: 13, LinkedIn: 9, Reddit: 8, X: 5 },
    topLeads: leads.slice(3, 6),
  },
  {
    date: "2026-02-20",
    totalLeads: 28,
    highIntent: 8,
    mediumIntent: 12,
    lowIntent: 8,
    platforms: { Facebook: 11, LinkedIn: 8, Reddit: 5, X: 4 },
    topLeads: leads.slice(6, 9),
  },
];
